print("hello world")
name = input("what is your name :")
print("hello," + name)
age =input("what is your age:")
print("hello" + name + " you are " + age + " years old ")
num_1 = int(input("enter the num1:"))
num_2 = int(input("enter the num2:"))
sum = (num_1 + num_2)
print(sum)
